### ISSUE TITLE
source code of mask generation

### ISSUE THREAD

**Issue by fzimmermann89** [CmrxRecon/CMRxRecon2024#3]
Hello,

for those teams not having access to matlab, it would be great if you could provide all matlab files as source (.m) instead of only providing encrypted .p files for some functions, such as the sampling pattern generation
https://github.com/CmrxRecon/CMRxRecon2024/blob/main/CMRxReconMaskGeneration/Task2/Toolbox_Mask_Generator_Task2/ktRadialSampling.p
If we can access .m files, we can reimplement it in python more easily.

Thank you,
Fellix

**Comment by wangziblake** [comment]
Hello,

Thanks for joining our challenge. I will upload the open-access .m files for all functions of mask generation within this week.
And then, I would appreciate it if you could contribute your well-implemented python version about mask generation to this repository.

Best,
Zi

**Comment by wangziblake** [comment]
Hi, please enjoy the source codes for all functions of mask generation!
Looking forward to your contribution to the well-implemented python version.

Best,
Zi

**Comment by fzimmermann89** [comment]
Thank you, just to confirm:
The pseudo-radial data will be on a non-square k-space, with _spoke lengths_ for different directions?
This does not match the illustrations in the challenge website, but the validation data.

So read-out oversampling will **NOT** be removed beforehand?

(This seems rather strange, especially considering that the 'raw data' does not look like raw data anyways but most likely pocs partial fourier reconstructed and coil compressed)

A more realistic radial fourier sampling approximation would have removed the oversampling to have all spokes with the same length, as no actual radial sampling would ever change the spoke length during a scan. 
Most likely it is too late to change that now, but please consider this as a) a severe limitation in a summary paper and b) as something that might be improved next year :)
